apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eks-portfolio
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/yubin05/eks-infra.git
    targetRevision: main
    path: k8s/overlays/dev

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
