apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    env: dev
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        env: dev
