apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: eks-portfolio-backend
    newName: <AWS_ACCOUNT_ID>.dkr.ecr.<AWS_REGION>.amazonaws.com/eks-portfolio-backend
    newTag: latest
  - name: eks-portfolio-frontend
    newName: <AWS_ACCOUNT_ID>.dkr.ecr.<AWS_REGION>.amazonaws.com/eks-portfolio-frontend
    newTag: latest

patchesStrategicMerge:
  - backend-deployment-patch.yaml
  - frontend-deployment-patch.yaml
